apiVersion: apps/v1

kind: Deployment

metadata:

  name: frontend

  labels:

    app: frontend

spec:

  replicas: 1

  selector:

    matchLabels:

      app: frontend

  template:

    metadata:

      labels:

        app: frontend

    spec:
      containers:
        - name: frontend
          image: hamzaennaji00/udagram-frontend:last
          ports:
            - containerPort: 80

