# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local hamzaennaji/udagram-frontend:v1
    - run: docker tag udagram-api-user hamzaennaji/udagram-api-user:v1
    - run: docker tag udagram-api-feed hamzaennaji/udagram-api-feed:v1
    - run: docker tag reverseproxy hamzaennaji/reverseproxy:v1
    - run: docker push hamzaennaji/udagram-api-user:v1
    - run: docker push hamzaennaji/udagram-frontend:v1
    - run: docker push hamzaennaji/udagram-api-feed:v1
    - run: docker push hamzaennaji/reverseproxy:v1
