# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker --version
    - run: docker build -t udagram-reverseproxy ./udagram-reverseproxy
    - run: docker tag udagram-reverseproxy hamzaennaji00/reverseproxy:latest
    - run: docker build -t udagram-api-user ./udagram-api-user
    - run: docker tag udagram-api-user hamzaennaji00/udagram-api-user:latest
    - run: docker build -t udagram-api-feed ./udagram-api-feed
    - run: docker tag udagram-api-feed hamzaennaji00/udagram-api-feed:latest
    - run: docker build -t udagram-frontend ./udagram-frontend
    - run: docker tag udagram-frontend hamzaennaji00/udagram-frontend:latest
    - run: echo "${{ secrets.DOCKER_PASSWORD }}". | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push hamzaennaji00/reverseproxy:latest
    - run: docker push hamzaennaji00/udagram-api-user:latest
    - run: docker push hamzaennaji00/udagram-api-feed:latest
    - run: docker push hamzaennaji00/udagram-frontend:latest
